version: "2"         # required to adjust maintainability checks

checks:
  method-complexity:
    enabled: true
    config:
      threshold: 7
  argument-count:
    enabled: true
    config:
      threshold: 5

exclude_patterns:
  - "benchmark/**/*"
  - "script/**/*"
  - "test/**/*"
