name: Performance Check

on: [pull_request]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        ruby: ['3.0', 3.1, 3.2]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true
    - name: Run benchmark
      run: |
        ruby script/perf_check.rb
